#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details
#

# Only run CI builds for these branches
trigger:
  branches:
    include:
    - 'master'
    - 'release/*'
    - 'internal/release/*'
# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

name: $(Date:yyyyMMdd).$(Rev:rr)

jobs:
- template: eng/templates/default-build.yml
  parameters:
    agentOs: Windows
    configuration: Release
    codeSign: true
    buildArgs: |
      '/p:PublishBlobFeedKey=$(PB_PublishBlobFeedKey)'
    artifacts:
      publish: true
      name: packages
      path: artifacts/Release/packages/

- template: eng/templates/default-build.yml
  parameters:
    agentOs: macOS
    configuration: Release

- template: eng/templates/default-build.yml
  parameters:
    agentOs: Linux
    configuration: Release

- job: Helix
  pool:
    name: Hosted VS2017
    vmImage: vs2017-win2016
  steps:
  - checkout: self
    clean: true
  - script: .\build.cmd -ci /t:Helix
    displayName: Run build.cmd helix target

